### ISSUE TITLE
Why/how does "chalk-format.js" work?

### ISSUE THREAD

**Issue by sebolio** [75lb/command-line-usage#41]
Hello, I've been trying to understand how you implemented the `{red text}` api, but i'm struggling to figure it out, since I can't find any reference to `raw` in `chalk`.

This is the source:
```js
function chalkFormat (str) {
  if (str) {
    str = str.replace(/`/g, '\\`')
    const chalk = require('chalk')
    return chalk(Object.assign([], {raw: [str]}))
  } else {
    return ''
  }
}
```
Which you can use like this
```js
chalkFormat('hello {red friend}')
```
and outputs this:
![image](https://user-images.githubusercontent.com/197329/218957442-7ce55b74-ace4-4523-91fa-e65b592b3605.png)

which is a simpler equivalent of using chalk:
```js
`hello ${chalk.red('friend')}`
```

Just for the sake of learning, could you please explain?
Thanks 😃

**Comment by 75lb** [comment]
[String.raw()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw).

A template literal, by definition since it's a literal, is statically declared in code. In this app, the template is passed into the app as string data. Using `string.raw()` is the only way I could find at the time to handle templates as string variables rather than literals.

Also, the user sometimes uses backticks in their usage guides (e.g. an option description of "this option accepts a \`string\`"), so command-line-usage must handle backticks in the input.
