### ISSUE TITLE
Content { options, data } is not documented

### ISSUE THREAD

**Issue by j-oliveras** [75lb/command-line-usage#7]
[Content documentation](https://github.com/75lb/command-line-usage#commandlineusagecontent) has no reference to [this possible content declaration](https://github.com/75lb/command-line-usage/blob/master/lib/content.js#L44) (object with options and data, both optionals but one required).

Reading the source code, I understand that the option object has the same type as [table-layout options](https://github.com/75lb/table-layout#tablelayoutdata-options-) and data has the same type as an array of objects decribed into Content document (the same as table-layout data).

Are my assumptions correct?

**Comment by 75lb** [comment]
hi, yes you are correct across the board.. i didn't document that particular use case for `Content` as i felt neither table-layout nor its docs were yet complete enough to expose to users.. however, it is still functional and i used it in a few of the examples.. feel free to use, since you figured it all out..

**Comment by j-oliveras** [comment]
Thanks.

**Comment by 75lb** [comment]
it's documented now
